### ISSUE TITLE
Error running ./mapmaker maps/circle/mapmaker.json output/circle

### ISSUE THREAD

**Issue by alan-wu** [dbrnz/mapmaker#1]
The error is as followed:

fs.js:885
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir 'output/circle'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Object.main (/home/alan/git_repos/mapmaker/src/mapmaker.js:315:12)
    at Object.<anonymous> (/home/alan/git_repos/mapmaker/mapmaker:5:10)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)

**Comment by dbrnz** [comment]
Hmm, what commands did you run? The following works for me:
```
git clone git@github.com:dbrnz/mapmaker
cd mapmaker
npm install
./mapmaker maps/circle/mapmaker.json output/circle
```

**Comment by alan-wu** [comment]
`git clone https://github.com/dbrnz/mapmaker.git ` instead but that should not make any difference.
I tested it on another machine and it worked fine. This is really strange.

**Comment by alan-wu** [comment]
Found out that the recursive flag used by mkdirSync is not support by my version of node, everything works fine after updating it. Thanks.
